[[redirects]]
  from = "/api/*"
  to = "https://ventifai-back-des-production.up.railway.app/:splat"
  status = 200
  force = true
  headers = {
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization"
  }
[build]
  command = "ng build --configuration production"
  publish = "dist/FRONT/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


